/**
 * tests/droplet-manifest.test.ts
 *
 * Covers scripts/lib/droplet-manifest.ts (the single source of truth for what
 * bootstrap-droplet.ts uploads) and the README table renderer in
 * scripts/sync-readme-manifest.ts.
 *
 * Two failure modes are defended: a manifest entry that silently never reaches
 * the README, and manifest data whose shape breaks either the Markdown table
 * or the uploader's destination-directory handling.
 *
 * Hermetic: reads repository files only; writes nothing and never invokes git
 * or the sync script's main().
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  required,
  optional,
  type ManifestEntry,
} from "../scripts/lib/droplet-manifest";
import { renderTable } from "../scripts/sync-readme-manifest";

const REPO_ROOT = path.resolve(__dirname, "..");
const BEGIN = "<!-- BEGIN: droplet-manifest -->";
const END = "<!-- END: droplet-manifest -->";
const HEADER = "| Path | Purpose | Phase | Tier |";
const SEPARATOR = "|------|---------|-------|------|";

const entry = (over: Partial<ManifestEntry> = {}): ManifestEntry => ({
  path: "droplet/example.sh",
  purpose: "Example",
  phase: "phase-9",
  destSubdir: "",
  chmodExec: true,
  ...over,
});

// ─── rendered table shape ────────────────────────────────────────────────────

test("renderTable wraps the table in the managed-section markers", () => {
  const lines = renderTable({ required, optional }).split("\n");
  assert.equal(lines[0], BEGIN);
  assert.equal(lines.at(-1), END);
  assert.match(lines[1], /^<!-- AUTO-GENERATED by /);
  assert.equal(lines[2], "", "a blank line must separate the comment from the table");
  assert.equal(lines.at(-2), "", "a blank line must separate the table from the END marker");
});

test("renderTable emits the fixed four-column header and separator", () => {
  const lines = renderTable({ required, optional }).split("\n");
  assert.equal(lines[3], HEADER);
  assert.equal(lines[4], SEPARATOR);
});

test("renderTable emits exactly one row per manifest entry and nothing else", () => {
  const lines = renderTable({ required, optional }).split("\n");
  // BEGIN + AUTOGEN + blank + header + separator + rows + blank + END
  assert.equal(lines.length, 7 + required.length + optional.length);
  const rows = lines.slice(5, 5 + required.length + optional.length);
  for (const r of rows) {
    assert.equal(r.split("|").length, 6, `row is not four columns: ${r}`);
  }
});

test("renderTable lists every manifest entry with its path, purpose, phase and tier", () => {
  const rendered = renderTable({ required, optional });
  for (const e of required) {
    assert.ok(
      rendered.includes(`| \`${e.path}\` | ${e.purpose} | ${e.phase} | required |`),
      `required entry missing from the rendered table: ${e.path}`
    );
  }
  for (const e of optional) {
    assert.ok(
      rendered.includes(`| \`${e.path}\` | ${e.purpose} | ${e.phase} | optional |`),
      `optional entry missing from the rendered table: ${e.path}`
    );
  }
});

test("renderTable renders required rows before optional rows", () => {
  const rendered = renderTable({
    required: [entry({ path: "droplet/req.sh" })],
    optional: [entry({ path: "droplet/opt.sh" })],
  });
  assert.ok(rendered.indexOf("droplet/req.sh") < rendered.indexOf("droplet/opt.sh"));
});

test("renderTable tags optional entries with the optional tier", () => {
  // `optional` is empty today, so only a synthetic manifest exercises the tier.
  const rendered = renderTable({
    required: [],
    optional: [entry({ path: "droplet/opt.sh", purpose: "Later", phase: "phase-9" })],
  });
  assert.ok(rendered.includes("| `droplet/opt.sh` | Later | phase-9 | optional |"));
  assert.ok(!rendered.includes("| required |"));
});

test("renderTable preserves manifest order rather than sorting", () => {
  const rendered = renderTable({
    required: [entry({ path: "droplet/z.sh" }), entry({ path: "droplet/a.sh" })],
    optional: [],
  });
  assert.ok(rendered.indexOf("droplet/z.sh") < rendered.indexOf("droplet/a.sh"));
});

test("renderTable renders an empty manifest as a header-only table", () => {
  const lines = renderTable({ required: [], optional: [] }).split("\n");
  assert.deepEqual(lines, [BEGIN, lines[1], "", HEADER, SEPARATOR, "", END]);
});

test("renderTable is a pure function of its input", () => {
  const manifest = { required, optional };
  assert.equal(renderTable(manifest), renderTable(manifest));
  assert.notEqual(
    renderTable(manifest),
    renderTable({ required: required.slice(1), optional })
  );
});

// ─── manifest data invariants ────────────────────────────────────────────────

test("every required manifest artifact exists in the repository", () => {
  // bootstrap-droplet.ts bails pre-flight on a missing required entry, which
  // is only discoverable against a live droplet without this check.
  for (const e of [...required, ...optional]) {
    assert.ok(
      fs.existsSync(path.join(REPO_ROOT, e.path)),
      `manifest lists a file that does not exist: ${e.path}`
    );
  }
});

test("no manifest field contains a pipe that would break the Markdown table", () => {
  for (const e of [...required, ...optional]) {
    for (const [field, value] of Object.entries({
      path: e.path,
      purpose: e.purpose,
      phase: e.phase,
    })) {
      assert.ok(!value.includes("|"), `${e.path}: ${field} contains a pipe`);
      assert.ok(!value.includes("\n"), `${e.path}: ${field} contains a newline`);
    }
  }
});

test("manifest paths are unique and rooted in droplet/", () => {
  const paths = [...required, ...optional].map((e) => e.path);
  assert.equal(new Set(paths).size, paths.length, "duplicate manifest path");
  for (const p of paths) {
    assert.ok(p.startsWith("droplet/"), `manifest path outside droplet/: ${p}`);
    assert.ok(!p.includes(".."), `manifest path escapes the tree: ${p}`);
  }
});

test("destSubdir is either empty or a trailing-slash-terminated relative dir", () => {
  // The uploader mkdir -p's destSubdir and concatenates it onto the remote
  // path, so a missing trailing slash would silently rename the artifact.
  for (const e of [...required, ...optional]) {
    if (e.destSubdir === "") continue;
    assert.ok(e.destSubdir.endsWith("/"), `destSubdir lacks a trailing slash: ${e.path}`);
    assert.ok(!e.destSubdir.startsWith("/"), `destSubdir is absolute: ${e.path}`);
  }
});

test("destSubdir agrees with the artifact's own location under droplet/", () => {
  for (const e of [...required, ...optional]) {
    assert.equal(
      e.path,
      `droplet/${e.destSubdir}${path.basename(e.path)}`,
      `destSubdir does not mirror the source path for ${e.path}`
    );
  }
});

test("every executable-flagged artifact is a shell script and vice versa", () => {
  for (const e of [...required, ...optional]) {
    assert.equal(
      e.chmodExec,
      e.path.endsWith(".sh"),
      `chmodExec disagrees with the artifact kind for ${e.path}`
    );
  }
});

test("the README managed section matches the current manifest", () => {
  // `npm run check:readme` enforces this against staged content in CI; this
  // catches drift locally without spawning git.
  const readme = fs.readFileSync(path.join(REPO_ROOT, "README.md"), "utf8");
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  assert.ok(begin !== -1 && end > begin, "README.md is missing the manifest markers");
  assert.equal(
    readme.slice(begin, end + END.length),
    renderTable({ required, optional })
  );
});
