/**
 * tests/parse-env-file.test.ts
 *
 * Covers `parseEnvFile()` in droplet/webhook-listener.js — the per-request
 * reader for /opt/github-backups/backup.env. It decides which allow/deny globs
 * the webhook path applies, so a mis-parse silently changes which repositories
 * get mirrored.
 *
 * Hermetic: fixtures are written under os.tmpdir() and removed afterwards;
 * requiring the listener does not start a server (its boot side effects are
 * entrypoint-only).
 */

import { test, after } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { createRequire } from "node:module";
import { envSlot } from "../scripts/bootstrap-droplet";

const LISTENER = path.resolve(__dirname, "..", "droplet", "webhook-listener.js");
const parseEnvFile: (filePath: string) => Record<string, string> =
  createRequire(__filename)(LISTENER).parseEnvFile;

const TMP = fs.mkdtempSync(path.join(os.tmpdir(), "gh-backup-envtest-"));
after(() => fs.rmSync(TMP, { recursive: true, force: true }));

let fixtureSeq = 0;
/** Write `content` verbatim (no trailing newline added) and parse it. */
function parse(content: string): Record<string, string> {
  const p = path.join(TMP, `backup.${fixtureSeq++}.env`);
  fs.writeFileSync(p, content, "utf8");
  return parseEnvFile(p);
}

// ─── basic shapes ────────────────────────────────────────────────────────────

test("parseEnvFile reads bare KEY=VALUE assignments", () => {
  assert.deepEqual(parse("GITHUB_TOKEN=ghp_abc123\nBACKUP_DIR=/opt/github-backups\n"), {
    GITHUB_TOKEN: "ghp_abc123",
    BACKUP_DIR: "/opt/github-backups",
  });
});

test("parseEnvFile strips exactly one matching pair of surrounding double quotes", () => {
  const env = parse('CRON_SCHEDULE="0 */6 * * *"\nGITHUB_SOURCES="acme other"\n');
  assert.equal(env.CRON_SCHEDULE, "0 */6 * * *");
  assert.equal(env.GITHUB_SOURCES, "acme other");
});

test("parseEnvFile keeps quotes that are not a matched surrounding pair", () => {
  const env = parse('A="unterminated\nB=trailing"\nC="a"b"\n');
  assert.equal(env.A, '"unterminated');
  assert.equal(env.B, 'trailing"');
  // Only the outermost pair is removed; inner quotes survive.
  assert.equal(env.C, 'a"b');
});

test("parseEnvFile turns an empty quoted value into an empty string", () => {
  const env = parse('GITHUB_SOURCE_ALLOW_ACME=""\nGITHUB_SOURCE_DENY_ACME=\n');
  assert.equal(env.GITHUB_SOURCE_ALLOW_ACME, "");
  assert.equal(env.GITHUB_SOURCE_DENY_ACME, "");
});

test('parseEnvFile does not mistake a lone `"` for a quoted value', () => {
  // A single quote character is length 1, so the strip must not fire and
  // produce an out-of-range slice.
  assert.equal(parse('A="\n').A, '"');
});

// ─── the value may itself contain `=` ────────────────────────────────────────

test("parseEnvFile splits on the first = and keeps later ones in the value", () => {
  const env = parse("A=b=c=d\nWEBHOOK_SECRET=abc=\n");
  assert.equal(env.A, "b=c=d");
  assert.equal(env.WEBHOOK_SECRET, "abc=");
});

// ─── line endings and whitespace ─────────────────────────────────────────────

test("parseEnvFile handles CRLF line endings without leaving a stray \\r", () => {
  const env = parse('A=1\r\nB="two words"\r\nC=3\r\n');
  assert.deepEqual(env, { A: "1", B: "two words", C: "3" });
});

test("parseEnvFile handles a file with no trailing newline", () => {
  assert.deepEqual(parse("A=1\nB=2"), { A: "1", B: "2" });
});

test("parseEnvFile trims surrounding whitespace on the line before parsing", () => {
  const env = parse('   A=1   \n\t B="two"\t\n');
  assert.equal(env.A, "1");
  assert.equal(env.B, "two");
});

test("parseEnvFile skips blank and whitespace-only lines", () => {
  assert.deepEqual(parse("\n\nA=1\n   \n\t\nB=2\n\n"), { A: "1", B: "2" });
});

// ─── comments and malformed lines ────────────────────────────────────────────

test("parseEnvFile skips comment lines, including indented ones and commented-out assignments", () => {
  const env = parse(
    "# Generated by bootstrap-droplet.ts — do not edit manually\n" +
      "   # Stored at /opt/github-backups/backup.env on the droplet (mode 600)\n" +
      "# CRON_SCHEDULE=0 3 * * *\n" +
      "#GITHUB_TOKEN=ghp_disabled\n" +
      "A=1\n"
  );
  assert.deepEqual(env, { A: "1" });
});

test("parseEnvFile treats a # after the start of a line as part of the value", () => {
  // There is no inline-comment syntax; `set -a; source` would keep the # too.
  assert.equal(parse("CRON_SCHEDULE=0 6 * * # not a comment\n").CRON_SCHEDULE, "0 6 * * # not a comment");
});

test("parseEnvFile skips lines with no = and lines whose key is empty", () => {
  const env = parse("JUSTAWORD\n=novalue\nA=1\n");
  assert.deepEqual(env, { A: "1" });
  assert.ok(!("" in env), "an empty key must never be recorded");
});

test("parseEnvFile does not strip an `export ` prefix", () => {
  // backup.env is generated without `export`; a prefixed line must not be
  // silently accepted under a wrong key name.
  const env = parse("export A=1\n");
  assert.equal(env.A, undefined);
  assert.equal(env["export A"], "1");
});

test("parseEnvFile performs no escape-sequence processing", () => {
  assert.equal(parse('A="a\\nb"\n').A, "a\\nb");
  assert.equal(parse("A=tab\\there\n").A, "tab\\there");
});

// ─── duplicate and missing keys ──────────────────────────────────────────────

test("parseEnvFile lets the last occurrence of a duplicate key win", () => {
  // `set -a; source` on the droplet has the same last-wins semantics, so the
  // webhook path must not diverge from the cron path.
  assert.equal(parse("A=first\nA=second\nA=third\n").A, "third");
});

test("parseEnvFile reports a missing key as undefined rather than throwing", () => {
  const env = parse("A=1\n");
  assert.equal(env.GITHUB_SOURCE_ALLOW_ACME, undefined);
});

test("parseEnvFile throws when the file does not exist so the caller fails closed", () => {
  assert.throws(
    () => parseEnvFile(path.join(TMP, "definitely-absent.env")),
    /ENOENT/
  );
});

// ─── cross-module contract with the backup.env writer ────────────────────────

test("parseEnvFile round-trips the exact line shapes bootstrap-droplet writes", () => {
  // Mirrors scripts/bootstrap-droplet.ts writeBackupEnv(): bare assignments for
  // the token/dir/hostname, quoted assignments for the space-separated lists.
  const sources = [
    { name: "acme-corp", allow: ["acme-corp/*"], deny: ["acme-corp/secret-*"] },
    { name: "solo.dev", allow: [], deny: [] },
  ];
  const lines = [
    "# Generated by bootstrap-droplet.ts — do not edit manually",
    "# Stored at /opt/github-backups/backup.env on the droplet (mode 600)",
    "GITHUB_TOKEN=ghp_TOKEN0000",
    `GITHUB_USER_OR_ORG=${sources[0].name}`,
    `GITHUB_SOURCES="${sources.map((s) => s.name).join(" ")}"`,
    ...sources.flatMap((s) => [
      `GITHUB_SOURCE_ALLOW_${envSlot(s.name)}="${s.allow.join(" ")}"`,
      `GITHUB_SOURCE_DENY_${envSlot(s.name)}="${s.deny.join(" ")}"`,
    ]),
    "BACKUP_DIR=/opt/github-backups",
    'CRON_SCHEDULE="0 */6 * * *"',
    `WEBHOOK_SECRET=${"a".repeat(64)}`,
    "WEBHOOK_HOSTNAME=backup.example.com",
  ];
  const env = parse(lines.join("\n") + "\n");

  assert.equal(env.GITHUB_TOKEN, "ghp_TOKEN0000");
  assert.equal(env.GITHUB_USER_OR_ORG, "acme-corp");
  assert.equal(env.GITHUB_SOURCES, "acme-corp solo.dev");
  assert.equal(env.GITHUB_SOURCE_ALLOW_ACME_CORP, "acme-corp/*");
  assert.equal(env.GITHUB_SOURCE_DENY_ACME_CORP, "acme-corp/secret-*");
  // An unfiltered source writes empty allow/deny, which the listener reads as
  // "no filter configured" → pass-through.
  assert.equal(env.GITHUB_SOURCE_ALLOW_SOLO_DEV, "");
  assert.equal(env.GITHUB_SOURCE_DENY_SOLO_DEV, "");
  assert.equal(env.CRON_SCHEDULE, "0 */6 * * *");
  assert.equal(env.WEBHOOK_SECRET, "a".repeat(64));
  assert.equal(env.WEBHOOK_HOSTNAME, "backup.example.com");
});

test("parseEnvFile preserves glob metacharacters in allow/deny lists verbatim", () => {
  const env = parse('GITHUB_SOURCE_ALLOW_ACME="a/* */b ?x [a-z]* !neg"\n');
  assert.equal(env.GITHUB_SOURCE_ALLOW_ACME, "a/* */b ?x [a-z]* !neg");
});
