#!/usr/bin/env node
/**
 * scripts/bootstrap-droplet.ts
 *
 * Uploads the droplet/ scripts and a generated backup.env to the droplet,
 * then runs bootstrap.sh remotely to install packages, configure GitHub CLI
 * authentication, and install the recurring backup cron job.
 *
 * Usage:
 *   GITHUB_TOKEN=<your_pat> npm run bootstrap-droplet
 *
 * Re-run safety (Phase 5 / TEARDOWN-01): on a droplet that has already
 * been bootstrapped, the on-droplet `backup.env` is preserved by default;
 * pass `--rotate-env` to force a fresh upload (PAT rotation, schedule change).
 * Droplet `*.sh` scripts are always overwritten and `bootstrap.sh` is re-run.
 *
 * Prerequisites:
 *   - .droplet.json must exist    (run `npm run create-droplet` first)
 *   - config.json must exist
 *   - GITHUB_TOKEN env var must be set on first-run or with --rotate-env
 */

import { spawnSync } from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import * as crypto from "crypto";
import { Config, bail, loadConfig, loadDropletInfo } from "./lib/config";
import { scpFile, sshFlags, sshRun, runCapture, waitForSsh } from "./lib/ssh";
import { required as manifestRequired, optional as manifestOptional } from "./lib/droplet-manifest";

// ─────────────────────────────────────────────────────────────────────────────
// backup.env generator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Source-name → env-var slot. Matches droplet/github-backup.sh's bash `slot()`
 * and droplet/webhook-listener.js's `envSlot()` byte-for-byte: uppercase, then
 * replace every non-alphanumeric char with `_`. NO trailing-underscore strip.
 */
export const envSlot = (n: string): string =>
  n.toUpperCase().replace(/[^A-Z0-9]/g, "_");

/**
 * Write a temporary backup.env to the OS temp dir.
 * Returns the path. The caller is responsible for deleting it.
 *
 * The file is created with mode 0600 to minimise the window during which
 * it is readable by other OS users on the local machine.
 *
 * WR-04: validate the token shape before emitting an unquoted shell
 * assignment. The droplet sources backup.env with `set -a; source`, so
 * any `$`, `"`, `\``, newline, or whitespace in the token would corrupt
 * the env or inject shell. GitHub PATs today are alnum + underscore;
 * bail loudly on anything else.
 *
 * Phase 3 additions: WEBHOOK_SECRET (64-hex) and WEBHOOK_HOSTNAME (FQDN)
 * are appended. Both shapes are validated here as a second line of defence;
 * loadConfig already enforces the FQDN, and resolveWebhookSecret guarantees
 * the 64-hex secret shape.
 */
function writeBackupEnv(
  cfg: Config,
  githubToken: string,
  webhookSecret: string
): string {
  if (!/^[A-Za-z0-9_]+$/.test(githubToken)) {
    bail(
      "GITHUB_TOKEN contains characters outside [A-Za-z0-9_] after trim.\n" +
        `    Length=${githubToken.length}. Refusing to write it to backup.env\n` +
        "    unquoted (would corrupt the env file or inject shell on the\n" +
        "    droplet). Confirm the token shape, then re-run."
    );
  }
  if (!/^[a-f0-9]{64}$/.test(webhookSecret)) {
    bail(
      `WEBHOOK_SECRET shape rejected (expected 64 hex chars, got len=${webhookSecret.length}).`
    );
  }

  // Phase 6: source list + per-source filter lines. cfg.sources is guaranteed
  // non-empty by loadConfig() (it bails if both githubUserOrOrg and
  // githubSources are missing/empty).
  const sourceNames = cfg.sources.map((s) => s.name);
  const legacyFirst = sourceNames[0]; // D-04 back-compat with not-yet-upgraded droplet

  const filterLines: string[] = [];
  for (const s of cfg.sources) {
    const slot = envSlot(s.name);
    filterLines.push(`GITHUB_SOURCE_ALLOW_${slot}="${s.allow.join(" ")}"`);
    filterLines.push(`GITHUB_SOURCE_DENY_${slot}="${s.deny.join(" ")}"`);
  }

  const lines = [
    `# Generated by bootstrap-droplet.ts — do not edit manually`,
    `# Stored at ${cfg.backupDir}/backup.env on the droplet (mode 600)`,
    `GITHUB_TOKEN=${githubToken}`,
    // Phase 6: legacy single-source line preserved (D-04). Always equals
    // sources[0].name so a not-yet-upgraded droplet keeps working.
    `GITHUB_USER_OR_ORG=${legacyFirst}`,
    // Phase 6: authoritative multi-source list (space-separated).
    `GITHUB_SOURCES="${sourceNames.join(" ")}"`,
    ...filterLines,
    `BACKUP_DIR=${cfg.backupDir}`,
    // Wrap schedule in quotes so it survives `source backup.env` correctly
    `CRON_SCHEDULE="${cfg.cronSchedule}"`,
    // Phase 3 — webhook listener env (D-07, D-19). Both values are shell-safe
    // by their validated shapes (64-hex and FQDN) so no quoting is needed.
    `WEBHOOK_SECRET=${webhookSecret}`,
    `WEBHOOK_HOSTNAME=${cfg.webhookHostname}`,
  ];

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "gh-backup-"));
  const envPath = path.join(tmpDir, "backup.env");
  fs.writeFileSync(envPath, lines.join("\n") + "\n", { mode: 0o600 });
  return envPath;
}

// ─────────────────────────────────────────────────────────────────────────────
// Webhook secret resolution (Phase 3 / D-07, D-09)
// ─────────────────────────────────────────────────────────────────────────────

interface ResolveSecretArgs {
  rotate: boolean;
  sshUser: string;
  sshKeyPath: string;
  dropletIp: string;
}

/**
 * Determine the WEBHOOK_SECRET to write into the new backup.env.
 *
 * Default (rotate=false):
 *   1. SSH to droplet, grep WEBHOOK_SECRET= from /opt/github-backups/backup.env.
 *   2. If a well-shaped 64-hex value is found, preserve it. No stdout echo.
 *   3. If missing or malformed, generate fresh. No stdout echo.
 *
 * --rotate-webhook-secret:
 *   Always regenerate fresh, print a re-register reminder. No stdout echo.
 *
 * The secret is never printed to stdout or stderr. It is written to
 * /opt/github-backups/backup.env (mode 0600) on the droplet, and
 * `npm run register-webhooks -- --update` retrieves it over SSH. This
 * helper itself neither caches nor persists it locally beyond the
 * in-process call to writeBackupEnv.
 */
function resolveWebhookSecret(args: ResolveSecretArgs): string {
  if (args.rotate) {
    const fresh = crypto.randomBytes(32).toString("hex");
    console.log(`\n🔁  --rotate-webhook-secret: regenerating WEBHOOK_SECRET`);
    console.log(
      `\n   New WEBHOOK_SECRET written to /opt/github-backups/backup.env (mode 0600) on the droplet.`
    );
    console.log(
      `   Need the raw value? ssh ${args.sshUser}@${args.dropletIp} 'grep ^WEBHOOK_SECRET= /opt/github-backups/backup.env'`
    );
    console.log(
      `\n   Reminder: run \`npm run register-webhooks -- --update\` to push the new secret to GitHub.\n`
    );
    return fresh;
  }
  // Read existing remote backup.env (if any) for the current secret.
  const cmd =
    `ssh ${sshFlags(args.sshKeyPath)} ${args.sshUser}@${args.dropletIp} ` +
    `'grep ^WEBHOOK_SECRET= /opt/github-backups/backup.env 2>/dev/null || true'`;
  let existing = "";
  try {
    existing = runCapture(cmd);
  } catch {
    existing = "";
  }
  if (existing.startsWith("WEBHOOK_SECRET=")) {
    const val = existing.slice("WEBHOOK_SECRET=".length).trim();
    if (/^[a-f0-9]{64}$/.test(val)) {
      console.log(
        `\n🔐  Preserving existing WEBHOOK_SECRET from droplet's backup.env`
      );
      return val;
    }
    console.log(
      `\n⚠️   Remote WEBHOOK_SECRET present but malformed (length=${val.length}); regenerating.`
    );
  }
  const fresh = crypto.randomBytes(32).toString("hex");
  console.log(`\n🆕  Generating fresh WEBHOOK_SECRET (first-run or missing-on-droplet)`);
  console.log(
    `\n   Written to /opt/github-backups/backup.env (mode 0600) on the droplet; ` +
      `\`npm run register-webhooks -- --update\` reads it over SSH.`
  );
  console.log(
    `   Need the raw value? ssh ${args.sshUser}@${args.dropletIp} 'grep ^WEBHOOK_SECRET= /opt/github-backups/backup.env'\n`
  );
  return fresh;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

function hasFlag(name: string): boolean {
  return process.argv.slice(2).includes(name);
}

/**
 * Determine the local commit deployed by this bootstrap run.
 *
 * Returns the full HEAD sha, or "unknown" when git is unavailable or the
 * command fails. Suffixes "-dirty" when `git status --porcelain` reports
 * uncommitted local changes, so the droplet marker reflects code that may
 * not match any committed sha.
 */
function resolveDeployedCommit(): string {
  let sha = "unknown";
  try {
    const r = spawnSync("git", ["rev-parse", "HEAD"], { encoding: "utf8" });
    if (r.status === 0) {
      const out = (r.stdout ?? "").trim();
      if (out) sha = out;
    }
  } catch {
    // best-effort; sha stays "unknown"
  }
  if (sha === "unknown") {
    return sha;
  }
  try {
    const status = spawnSync("git", ["status", "--porcelain"], { encoding: "utf8" });
    if (status.status === 0 && (status.stdout ?? "").trim() !== "") {
      sha = `${sha}-dirty`;
    }
  } catch {
    // best-effort; treat as clean
  }
  return sha;
}

async function main(): Promise<void> {
  // NR-05: trim before checking. A trailing CR (Windows-line-ending file
  // piped into GITHUB_TOKEN=$(cat token.txt)) or wrapping whitespace
  // (`export GITHUB_TOKEN=" ghp_xxx "` from shell history) would
  // otherwise pass the presence check and then fail the shape check
  // inside writeBackupEnv with a confusing "characters outside" error
  // on a token the operator "knows is right".
  //
  // Phase 5 / TEARDOWN-01 D-01..D-04: the eager unconditional bail-on-empty
  // moved into the upload branch below. Re-runs that preserve the existing
  // backup.env do not need a token in the operator's shell.
  const githubToken = (process.env["GITHUB_TOKEN"] ?? "").trim();

  const rotateWebhook = hasFlag("--rotate-webhook-secret");
  const rotateEnv = hasFlag("--rotate-env");

  const cfg = loadConfig();
  const droplet = loadDropletInfo();
  const { ip, name } = droplet;
  const { sshUser: user, sshKeyPath: keyPath, backupDir } = cfg;

  console.log(`\n📦  Bootstrapping droplet "${name}" (${ip})…`);

  // ─── Phase 8 MANIFEST-01/02 (D-03 step 1): pre-flight required-file check ─
  // Iterate manifest.required and bail on the first miss BEFORE any SSH/scp.
  // Bail message wording is the contract from ROADMAP Phase 8 SC#2.
  for (const entry of manifestRequired) {
    const abs = path.resolve(process.cwd(), entry.path);
    if (!fs.existsSync(abs)) {
      bail(`missing required artifact: ${entry.path}`);
    }
  }

  await waitForSsh(ip, user, keyPath);

  console.log(`\n📁  Creating remote directory: ${backupDir}`);
  sshRun(ip, user, keyPath, `mkdir -p "${backupDir}"`);

  const deployedCommit = resolveDeployedCommit();
  console.log(`\n🏷️   Writing deployed-commit marker: ${deployedCommit}`);
  sshRun(
    ip,
    user,
    keyPath,
    `printf "%s\\n" "${deployedCommit}" > "${backupDir}/.deployed-commit" && chmod 0644 "${backupDir}/.deployed-commit"`
  );

  // First-run probe (D-03): the on-droplet backup.env is the only
  // authoritative signal of "has this droplet been bootstrapped before".
  // Probe failure (SSH transport error, exit 255) propagates out of
  // runCapture and bails — never silently treat as "absent" (would let a
  // network blip overwrite the operator's active token).
  const probeCmd =
    `ssh ${sshFlags(keyPath)} ${user}@${ip} ` +
    `'test -f "${backupDir}/backup.env" && echo present || echo absent'`;
  const probe = runCapture(probeCmd).trim();
  if (probe !== "present" && probe !== "absent") {
    bail(
      `Unexpected probe response from droplet: ${JSON.stringify(probe)}.\n` +
        `    Expected 'present' or 'absent'. Aborting to avoid clobbering backup.env.`
    );
  }
  const envExists = probe === "present";
  // --rotate-webhook-secret is only honoured by the upload branch below, so it
  // must open that branch on its own. Otherwise the flag is a silent no-op on
  // an already-bootstrapped droplet: the operator is told the secret rotated
  // while the droplet keeps the old one and GitHub keeps signing with it.
  const willUpload = !envExists || rotateEnv || rotateWebhook;

  if (willUpload) {
    if (!githubToken) {
      const hint =
        rotateEnv || rotateWebhook
          ? ` (${rotateEnv ? "--rotate-env" : "--rotate-webhook-secret"} rewrites backup.env, which requires GITHUB_TOKEN)`
          : "";
      bail(
        "GITHUB_TOKEN environment variable is not set (or is empty after trim).\n" +
          "    Usage: GITHUB_TOKEN=<your_pat> npm run bootstrap-droplet" +
          hint
      );
    }

    // ── Resolve webhook secret (preserve on re-bootstrap, opt-in rotation) ──
    // D-07/D-09: default path reads the existing WEBHOOK_SECRET over SSH and
    // preserves it (so registered GitHub webhooks keep working across re-runs).
    // --rotate-webhook-secret generates a fresh value, writes it to the
    // droplet's backup.env (never echoed), and reminds the operator to
    // re-push it to GitHub via register-webhooks --update.
    const webhookSecret = resolveWebhookSecret({
      rotate: rotateWebhook,
      sshUser: user,
      sshKeyPath: keyPath,
      dropletIp: ip,
    });

    console.log(`\n📝  Generating backup.env…`);
    const envPath = writeBackupEnv(cfg, githubToken, webhookSecret);

    try {
      console.log(`\n🔑  Uploading backup.env…`);
      scpFile(ip, user, keyPath, envPath, `${backupDir}/backup.env`);
    } finally {
      // Always delete the local temp file containing the token
      const tmpDir = path.dirname(envPath);
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  } else {
    // D-04: announce skip explicitly. Operator must never wonder whether
    // their token survived.
    console.log(
      `\n▸  ${backupDir}/backup.env exists on droplet — preserving ` +
        `(use --rotate-env to overwrite).`
    );
  }

  console.log(`\n📤  Uploading droplet scripts…`);
  const dropletDir = path.resolve(process.cwd(), "droplet");
  if (!fs.existsSync(dropletDir)) {
    bail("droplet/ directory not found in the project root.");
  }

  // ─── Phase 8 MANIFEST-01/02 (D-03 steps 2 + 3): manifest-driven upload ───
  // Required entries are guaranteed present by the pre-flight loop above;
  // optional entries warn-and-skip on miss. mkdir -p any destSubdir once
  // before scp'ing into it (preserves Phase 6 behaviour for `lib/` and lets
  // future phases drop artifacts in arbitrary sub-paths without editing
  // this file).
  const seenSubdirs = new Set<string>();
  for (const entry of manifestRequired) {
    if (entry.destSubdir && !seenSubdirs.has(entry.destSubdir)) {
      const subdir = entry.destSubdir.replace(/\/+$/, "");
      sshRun(ip, user, keyPath, `mkdir -p "${backupDir}/${subdir}"`);
      seenSubdirs.add(entry.destSubdir);
    }
    const src = path.resolve(process.cwd(), entry.path);
    const dst = `${backupDir}/${entry.destSubdir}${path.basename(entry.path)}`;
    console.log(`   → ${entry.destSubdir}${path.basename(entry.path)}`);
    scpFile(ip, user, keyPath, src, dst);
  }

  for (const entry of manifestOptional) {
    const src = path.resolve(process.cwd(), entry.path);
    if (!fs.existsSync(src)) {
      console.warn(`   ⚠ optional artifact not shipped: ${entry.path}`);
      continue;
    }
    if (entry.destSubdir && !seenSubdirs.has(entry.destSubdir)) {
      const subdir = entry.destSubdir.replace(/\/+$/, "");
      sshRun(ip, user, keyPath, `mkdir -p "${backupDir}/${subdir}"`);
      seenSubdirs.add(entry.destSubdir);
    }
    const dst = `${backupDir}/${entry.destSubdir}${path.basename(entry.path)}`;
    console.log(`   → ${entry.destSubdir}${path.basename(entry.path)} (optional)`);
    scpFile(ip, user, keyPath, src, dst);
  }

  console.log(`\n🚀  Running bootstrap.sh on the droplet…`);
  console.log("─".repeat(60));
  sshRun(
    ip,
    user,
    keyPath,
    `chmod +x ${backupDir}/*.sh && ${backupDir}/bootstrap.sh`
  );
  console.log("─".repeat(60));

  console.log(`\n✅  Bootstrap complete!`);
  console.log(`\n   SSH into the droplet:`);
  console.log(`   ssh -i ${cfg.sshKeyPath} ${user}@${ip}`);
  console.log(`\n   Trigger a backup manually:`);
  console.log(
    `   ssh -i ${cfg.sshKeyPath} ${user}@${ip} "${backupDir}/github-backup.sh"`
  );
  console.log(`\n   Watch the backup log:`);
  console.log(
    `   ssh -i ${cfg.sshKeyPath} ${user}@${ip} "tail -f /var/log/github-backup.log"\n`
  );
}

if (require.main === module) {
  main().catch((err) => {
    console.error(`\n❌  ${err instanceof Error ? err.message : err}\n`);
    process.exit(1);
  });
}
