#!/usr/bin/env node
/**
 * scripts/bootstrap-droplet.ts
 *
 * Uploads the droplet/ scripts and a generated backup.env to the droplet,
 * then runs bootstrap.sh remotely to install packages, configure GitHub CLI
 * authentication, and install the recurring backup cron job.
 *
 * Usage:
 *   GITHUB_TOKEN=<your_pat> npm run bootstrap-droplet
 *
 * The script is fully idempotent — running it again will overwrite scripts
 * and re-run bootstrap.sh, which is itself idempotent.
 *
 * Prerequisites:
 *   - .droplet.json must exist    (run `npm run create-droplet` first)
 *   - config.json must exist
 *   - GITHUB_TOKEN env var must be set
 */

import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { Config, bail, loadConfig, loadDropletInfo } from "./lib/config";
import { scpFile, sshRun, waitForSsh } from "./lib/ssh";

// ─────────────────────────────────────────────────────────────────────────────
// backup.env generator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Write a temporary backup.env to the OS temp dir.
 * Returns the path. The caller is responsible for deleting it.
 *
 * The file is created with mode 0600 to minimise the window during which
 * it is readable by other OS users on the local machine.
 *
 * WR-04: validate the token shape before emitting an unquoted shell
 * assignment. The droplet sources backup.env with `set -a; source`, so
 * any `$`, `"`, `\``, newline, or whitespace in the token would corrupt
 * the env or inject shell. GitHub PATs today are alnum + underscore;
 * bail loudly on anything else.
 */
function writeBackupEnv(cfg: Config, githubToken: string): string {
  if (!/^[A-Za-z0-9_]+$/.test(githubToken)) {
    bail(
      "GITHUB_TOKEN contains characters outside [A-Za-z0-9_].\n" +
        "    Refusing to write it to backup.env unquoted (would corrupt the env\n" +
        "    file or inject shell on the droplet). Trim whitespace/newlines and\n" +
        "    confirm the token shape, then re-run."
    );
  }

  const lines = [
    `# Generated by bootstrap-droplet.ts — do not edit manually`,
    `# Stored at ${cfg.backupDir}/backup.env on the droplet (mode 600)`,
    `GITHUB_TOKEN=${githubToken}`,
    `GITHUB_USER_OR_ORG=${cfg.githubUserOrOrg}`,
    `BACKUP_DIR=${cfg.backupDir}`,
    // Wrap schedule in quotes so it survives `source backup.env` correctly
    `CRON_SCHEDULE="${cfg.cronSchedule}"`,
  ];

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "gh-backup-"));
  const envPath = path.join(tmpDir, "backup.env");
  fs.writeFileSync(envPath, lines.join("\n") + "\n", { mode: 0o600 });
  return envPath;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const githubToken = process.env["GITHUB_TOKEN"] ?? "";
  if (!githubToken) {
    bail(
      "GITHUB_TOKEN environment variable is not set.\n" +
        "    Usage: GITHUB_TOKEN=<your_pat> npm run bootstrap-droplet"
    );
  }

  const cfg = loadConfig();
  const droplet = loadDropletInfo();
  const { ip, name } = droplet;
  const { sshUser: user, sshKeyPath: keyPath, backupDir } = cfg;

  console.log(`\n📦  Bootstrapping droplet "${name}" (${ip})…`);

  await waitForSsh(ip, user, keyPath);

  console.log(`\n📝  Generating backup.env…`);
  const envPath = writeBackupEnv(cfg, githubToken);

  try {
    console.log(`\n📁  Creating remote directory: ${backupDir}`);
    sshRun(ip, user, keyPath, `mkdir -p "${backupDir}"`);

    console.log(`\n🔑  Uploading backup.env…`);
    scpFile(ip, user, keyPath, envPath, `${backupDir}/backup.env`);

    console.log(`\n📤  Uploading droplet scripts…`);
    const dropletDir = path.resolve(process.cwd(), "droplet");
    if (!fs.existsSync(dropletDir)) {
      bail("droplet/ directory not found in the project root.");
    }

    const scriptFiles = fs
      .readdirSync(dropletDir, { withFileTypes: true })
      .filter((d) => d.isFile() && d.name.endsWith(".sh"))
      .map((d) => path.join(dropletDir, d.name));

    for (const file of scriptFiles) {
      const basename = path.basename(file);
      console.log(`   → ${basename}`);
      scpFile(ip, user, keyPath, file, `${backupDir}/${basename}`);
    }

    console.log(`\n🚀  Running bootstrap.sh on the droplet…`);
    console.log("─".repeat(60));
    sshRun(
      ip,
      user,
      keyPath,
      `chmod +x ${backupDir}/*.sh && ${backupDir}/bootstrap.sh`
    );
    console.log("─".repeat(60));
  } finally {
    // Always delete the local temp file containing the token
    const tmpDir = path.dirname(envPath);
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }

  console.log(`\n✅  Bootstrap complete!`);
  console.log(`\n   SSH into the droplet:`);
  console.log(`   ssh -i ${cfg.sshKeyPath} ${user}@${ip}`);
  console.log(`\n   Trigger a backup manually:`);
  console.log(
    `   ssh -i ${cfg.sshKeyPath} ${user}@${ip} "${backupDir}/github-backup.sh"`
  );
  console.log(`\n   Watch the backup log:`);
  console.log(
    `   ssh -i ${cfg.sshKeyPath} ${user}@${ip} "tail -f /var/log/github-backup.log"\n`
  );
}

main().catch((err) => {
  console.error(`\n❌  ${err instanceof Error ? err.message : err}\n`);
  process.exit(1);
});
