#!/usr/bin/env node
/**
 * scripts/sync-readme-manifest.ts
 *
 * Phase 8 (MANIFEST-03 / D-05): renders the droplet-manifest Markdown table
 * from `scripts/lib/droplet-manifest.ts` into the managed section of README.md
 * delimited by `<!-- BEGIN: droplet-manifest -->` / `<!-- END: droplet-manifest -->`.
 *
 * Usage:
 *   npm run sync:readme                    # rewrite README.md (idempotent)
 *   npm run sync:readme -- --check         # exit non-zero if README would change
 *   tsx scripts/sync-readme-manifest.ts --check --staged
 *                                           # same, but reads README.md and
 *                                           # droplet-manifest.ts from the git
 *                                           # index (falling back to HEAD) instead
 *                                           # of the working tree — this is what
 *                                           # scripts/git-hooks/pre-commit runs, so
 *                                           # it validates the commit that is about
 *                                           # to land, not whatever is on disk.
 *
 * Single source of truth = `scripts/lib/droplet-manifest.ts`. If the markers
 * are missing, the script bails with operator-actionable instructions.
 */

import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { execFileSync } from "child_process";
import { pathToFileURL } from "url";
import { required, optional, type ManifestEntry } from "./lib/droplet-manifest";

const README = path.resolve(process.cwd(), "README.md");
const MANIFEST_SRC = path.resolve(__dirname, "lib", "droplet-manifest.ts");
const BEGIN = "<!-- BEGIN: droplet-manifest -->";
const END = "<!-- END: droplet-manifest -->";
const AUTOGEN =
  "<!-- AUTO-GENERATED by `npm run sync:readme` from scripts/lib/droplet-manifest.ts — DO NOT EDIT BY HAND -->";

export interface Manifest {
  required: ManifestEntry[];
  optional: ManifestEntry[];
}

function bail(msg: string): never {
  console.error(`\n❌  ${msg}\n`);
  process.exit(1);
}

function row(e: ManifestEntry, tier: "required" | "optional"): string {
  return `| \`${e.path}\` | ${e.purpose} | ${e.phase} | ${tier} |`;
}

export function renderTable(manifest: Manifest): string {
  const header =
    "| Path | Purpose | Phase | Tier |\n" +
    "|------|---------|-------|------|";
  const lines: string[] = [];
  for (const e of manifest.required) lines.push(row(e, "required"));
  for (const e of manifest.optional) lines.push(row(e, "optional"));
  return [BEGIN, AUTOGEN, "", header, ...lines, "", END].join("\n");
}

/** `git show <object>`, relative to process.cwd(). Returns null instead of throwing. */
function gitShow(object: string): string | null {
  try {
    return execFileSync("git", ["show", object], {
      cwd: process.cwd(),
      encoding: "utf8",
    });
  } catch {
    return null;
  }
}

/**
 * Reads a tracked file's content as staged in the index (`:path`), falling
 * back to the HEAD commit if the path has no index entry (e.g. staged for
 * deletion) and to `null` if neither exists — which also covers the initial
 * commit, where `HEAD` itself does not resolve yet.
 */
function readStagedOrHead(relPath: string): string | null {
  const staged = gitShow(`:${relPath}`);
  if (staged !== null) return staged;
  return gitShow(`HEAD:${relPath}`);
}

function readStagedReadme(): string {
  const relPath = path.relative(process.cwd(), README);
  const content = readStagedOrHead(relPath);
  if (content === null) {
    bail(`README.md is not present in the git index or at HEAD (relative path: ${relPath}).`);
  }
  return content;
}

/**
 * Loads `required`/`optional` from the staged (or HEAD-committed) blob of
 * droplet-manifest.ts rather than the working-tree copy already imported
 * above, so `--staged` reflects exactly what this commit contains even if
 * the working tree has further unstaged edits to the manifest.
 */
async function loadStagedManifest(): Promise<Manifest> {
  const relPath = path.relative(process.cwd(), MANIFEST_SRC);
  const content = readStagedOrHead(relPath);
  if (content === null) {
    bail(`scripts/lib/droplet-manifest.ts is not present in the git index or at HEAD (relative path: ${relPath}).`);
  }
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "sync-readme-manifest-"));
  const tmpFile = path.join(tmpDir, "droplet-manifest.ts");
  try {
    fs.writeFileSync(tmpFile, content, "utf8");
    // Dynamic import: the module path is a temp file materialized from a git
    // blob at runtime, so it cannot be a static specifier known at author time.
    const mod = await import(pathToFileURL(tmpFile).href);
    return { required: mod.required, optional: mod.optional };
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const staged = args.includes("--staged");

  if (staged && !check) {
    bail("--staged only supports --check; there is nothing sensible to write for staged content.");
  }

  const manifest: Manifest = staged ? await loadStagedManifest() : { required, optional };

  let current: string;
  if (staged) {
    current = readStagedReadme();
  } else {
    if (!fs.existsSync(README)) bail("README.md not found in project root.");
    current = fs.readFileSync(README, "utf8");
  }

  const beginIdx = current.indexOf(BEGIN);
  const endIdx = current.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    bail(
      `README.md${staged ? " (staged)" : ""} is missing the droplet-manifest markers. ` +
        "Add the following two lines where the manifest table should appear:\n" +
        `  ${BEGIN}\n  ${END}\n` +
        "Then re-run npm run sync:readme."
    );
  }
  const before = current.slice(0, beginIdx);
  const after = current.slice(endIdx + END.length);
  const next = before + renderTable(manifest) + after;
  if (next === current) {
    console.log(`✓ README.md droplet-manifest section already up to date${staged ? " (staged)" : ""}.`);
    return;
  }
  if (check) {
    console.error(
      `✗ README.md droplet-manifest section is stale${staged ? " in the staged commit" : ""}. ` +
        `Run \`npm run sync:readme\`${staged ? " and re-stage README.md" : ""} and re-commit.`
    );
    process.exit(1);
  }
  fs.writeFileSync(README, next, "utf8");
  console.log(
    `✓ Updated README.md droplet-manifest section (${manifest.required.length + manifest.optional.length} entries).`
  );
}

if (require.main === module) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
