#!/usr/bin/env node
/**
 * scripts/sync-readme-manifest.ts
 *
 * Phase 8 (MANIFEST-03 / D-05): renders the droplet-manifest Markdown table
 * from `scripts/lib/droplet-manifest.ts` into the managed section of README.md
 * delimited by `<!-- BEGIN: droplet-manifest -->` / `<!-- END: droplet-manifest -->`.
 *
 * Usage:
 *   npm run sync:readme            # rewrite README.md (idempotent)
 *   npm run sync:readme -- --check # exit non-zero if README would change
 *
 * Single source of truth = `scripts/lib/droplet-manifest.ts`. If the markers
 * are missing, the script bails with operator-actionable instructions.
 */

import * as fs from "fs";
import * as path from "path";
import { required, optional, type ManifestEntry } from "./lib/droplet-manifest";

const README = path.resolve(process.cwd(), "README.md");
const BEGIN = "<!-- BEGIN: droplet-manifest -->";
const END = "<!-- END: droplet-manifest -->";
const AUTOGEN =
  "<!-- AUTO-GENERATED by `npm run sync:readme` from scripts/lib/droplet-manifest.ts — DO NOT EDIT BY HAND -->";

function bail(msg: string): never {
  console.error(`\n❌  ${msg}\n`);
  process.exit(1);
}

function row(e: ManifestEntry, tier: "required" | "optional"): string {
  return `| \`${e.path}\` | ${e.purpose} | ${e.phase} | ${tier} |`;
}

function renderTable(): string {
  const header =
    "| Path | Purpose | Phase | Tier |\n" +
    "|------|---------|-------|------|";
  const lines: string[] = [];
  for (const e of required) lines.push(row(e, "required"));
  for (const e of optional) lines.push(row(e, "optional"));
  return [BEGIN, AUTOGEN, "", header, ...lines, "", END].join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  if (!fs.existsSync(README)) bail("README.md not found in project root.");
  const current = fs.readFileSync(README, "utf8");
  const beginIdx = current.indexOf(BEGIN);
  const endIdx = current.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    bail(
      "README.md is missing the droplet-manifest markers. " +
        "Add the following two lines where the manifest table should appear:\n" +
        `  ${BEGIN}\n  ${END}\n` +
        "Then re-run npm run sync:readme."
    );
  }
  const before = current.slice(0, beginIdx);
  const after = current.slice(endIdx + END.length);
  const next = before + renderTable() + after;
  if (next === current) {
    console.log("✓ README.md droplet-manifest section already up to date.");
    return;
  }
  if (check) {
    console.error(
      "✗ README.md droplet-manifest section is stale. " +
        "Run `npm run sync:readme` and re-commit."
    );
    process.exit(1);
  }
  fs.writeFileSync(README, next, "utf8");
  console.log(
    `✓ Updated README.md droplet-manifest section (${required.length + optional.length} entries).`
  );
}

main();
